### PR TITLE
Fix missing find_package in tests

### PR DESCRIPTION
**Pull request by olivier-roussel**
Adds missing find_package for the Sofa.Testing component used in tests.

### CODE REVIEW

**Comment by olivier-roussel** [comment]
Test binary fails to link ( https://github.com/SofaDefrost/SoftRobots.Inverse/actions/runs/6430208124/job/17460765037?pr=9#step:7:1147 )
Maybe trying to link with deprecated code due to recent changes in SOFA master ?
```
/usr/bin/ld: /home/runner/work/SoftRobots.Inverse/SoftRobots.Inverse/SoftRobots/lib/libSoftRobots.so.1.0: undefined reference to `non-virtual thunk to sofa::core::behavior::MixedInteractionForceField<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double>, sofa::defaulttype::StdRigidTypes<3u, double> >::getClass() const'
/usr/bin/ld: /home/runner/work/SoftRobots.Inverse/SoftRobots.Inverse/SoftRobots/lib/libSoftRobots.so.1.0: undefined reference to `non-virtual thunk to sofa::core::behavior::ForceField<sofa::defaulttype::StdRigidTypes<3u, double> >::getClass() const'
/usr/bin/ld: /home/runner/work/SoftRobots.Inverse/SoftRobots.Inverse/SoftRobots/lib/libSoftRobots.so.1.0: undefined reference to `non-virtual thunk to sofa::core::behavior::ForceField<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::getClass() const'
``

**Comment by alxbilger** [comment]
I am convinced the problem is related to its dependency to SoftRobots. The error is on `PartialRigidificationForceField`. The only thing that I would change in this class is to add an include to `MixedInteractionForceField.inl` in `PartialRigidificationForceField.inl`.
Otherwise, I would check which version of the SoftRobots plugin is retrieved on the CI.

**Comment by olivier-roussel** [comment]
Oh yes you are tight, the linking error is related to SoftRobots.
The CI is getting the `master` release of SoftRobots plugin, which is what we expect.
I'll check your suggestion for the missing include.

**Comment by olivier-roussel** [comment]
I have to dig a bit more as it compiles locally with SoftRobots from master, so despite it gets "master" archives in the CI, I have to check that they are correctly set to master and understand what is going on.

**Comment by olivier-roussel** [comment]
Still don't get why I can't reproduce locally. I tried with the archive that is used of SoftRobots to check it was the proper version, and it seems.
May it be something related to gcc version used in the CI ?

**Comment by EulalieCoevoet** [comment]
These changes have been integrated with #12.

**Pull request closed without merging**
