### PR TITLE
[ci] update ci.yml

### PR DESCRIPTION
**Pull request by EulalieCoevoet**

### CODE REVIEW

**Comment by EulalieCoevoet** [comment]
@olivier-roussel Hello Olivier, I'm sorry I've duplicated what you were doing in #9, I forgot about this PR. 

In addition there is a bit of cleaning and I propose to use `sofa_with_sofapython3: 'true'` instead of looking for the release. SoftRobots CI is now working and has the master release needed for SoftRobots.Inverse CI to work.

The only [remaining problem is the tests run on Windows](https://github.com/SofaDefrost/SoftRobots.Inverse/actions/runs/7459922772/job/20298237266?pr=12) and I have no idea of what could be wrong. Is that the same problem you were having? (the logs have been deleted)

**Comment by olivier-roussel** [comment]
Hi @EulalieCoevoet, ok nice, I think I was not aware of `sofa_with_sofapython3` option for the github CI. 
I don't think this is same bug I had, I don't remind it exactly since it's been a while, but I think if I got this error 127 (which looks like telling the test binary does not exists or is not executable), I would most probably have checked if the file actually exists (it looks like it is linked successfully [in the logs] (https://github.com/SofaDefrost/SoftRobots.Inverse/actions/runs/7459922772/job/20298237266?pr=12#step:6:473) by adding some `ls` commands [here in the CI] (https://github.com/SofaDefrost/SoftRobots.Inverse/blob/f0414af48ae513d9af9e9e2b103f2b8d228057d6/.github/workflows/ci.yml#L154) to understand what is going on (maybe the binary is in some `$WORKSPACE_BUILD_PATH\tests\bin` instead of `$WORKSPACE_BUILD_PATH\bin` for example ?, as some testing related code has probably changed). And I guess I would remember having doing so if I did.

**Comment by EulalieCoevoet** [comment]
> The only things that come to my mind is that the LD_LIBRARY_PATH variable [here](https://github.com/SofaDefrost/SoftRobots.Inverse/actions/runs/7462790546/job/20305959630?pr=12#step:11:40) looks like to be defined as a list of paths separated by `:`, but I guess it should be `;` on Windows to avoid confusion with drive letter such as `D:`. 

It seems okay here https://github.com/SofaDefrost/SoftRobots/actions/runs/7448042980/job/20261540240

**Comment by EulalieCoevoet** [comment]
@olivier-roussel what's your OS ? If windows, does SoftRobots.Inverse_test.exe run on your computer ?

**Comment by olivier-roussel** [comment]
No I'm running linux

**Comment by EulalieCoevoet** [comment]
Hello @alxbilger, could you try SoftRobots.Inverse_test.exe on your machine ?

**Comment by EulalieCoevoet** [comment]
Well let's merge, so that it works at least on ubuntu and macos.

**Pull request merged**
